# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('given_name', models.CharField(default='', max_length=60)),
                ('last_name', models.CharField(default='', max_length=60)),
                ('middle_name', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
